export const GET_CITIES_REQUEST = 'GET_CITIES_REQUEST';
export const GET_CITIES_RESPONSE = 'GET_CITIES_RESPONSE';
export const GET_CITIES_FAIL = 'GET_CITIES_FAIL';

export const GET_WEATHER_REQUEST = 'GET_WEATHER_REQUEST';
export const GET_WEATHER_RESPONSE = 'GET_WEATHER_RESPONSE';
export const GET_WEATHER_FAIL = 'GET_WEATHER_FAIL';
